"use client";
import {useState} from "react";
const API=process.env.NEXT_PUBLIC_API_BASE_URL||"http://localhost:8000";
export default function Home(){
 const [resume,setResume]=useState(""),[jd,setJd]=useState(""),[score,setScore]=useState<any>(null),[selected,setSelected]=useState(""),[suggestion,setSuggestion]=useState(""),[history,setHistory]=useState<string[]>([]),[future,setFuture]=useState<string[]>([]);
 async function upload(file:File){const f=new FormData();f.append("file",file);const r=await fetch(API+"/parse-resume",{method:"POST",body:f});const d=await r.json();if(!r.ok){alert(d.detail||"Upload failed");return}setResume(d.text);setScore(null)}
 async function scan(){const r=await fetch(API+"/analyze",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({resume_text:resume,job_description:jd})});setScore(await r.json())}
 async function fix(){const r=await fetch(API+"/suggest-fix",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({current_text:selected,resume_text:resume,job_description:jd})});setSuggestion((await r.json()).suggestion)}
 function apply(){if(!suggestion||!selected)return;setHistory([...history,resume]);setFuture([]);setResume(resume.replace(selected,suggestion));setSelected("");setSuggestion("")}
 function undo(){if(!history.length)return;setFuture([resume,...future]);setResume(history.at(-1)!);setHistory(history.slice(0,-1))}
 function redo(){if(!future.length)return;setHistory([...history,resume]);setResume(future[0]);setFuture(future.slice(1))}
 return <main className="shell"><header><div><small>PRIVATE • LOCAL ONLY</small><h1>Personal Resume ATS Optimizer</h1><p>Improve your resume against a job description without inventing experience.</p></div><label>Resume PDF/DOCX<input type="file" accept=".pdf,.docx" onChange={e=>e.target.files?.[0]&&upload(e.target.files[0])}/></label></header><section className="jd"><label>JOB DESCRIPTION</label><textarea value={jd} onChange={e=>setJd(e.target.value)} placeholder="Paste target job description..."/><button className="primary" onClick={scan} disabled={!resume||!jd}>Scan Resume</button></section><section className="grid"><div className="panel"><div className="bar"><label>RESUME</label><div><button onClick={undo} disabled={!history.length}>Undo</button> <button onClick={redo} disabled={!future.length}>Redo</button></div></div><textarea className="resume" value={resume} onChange={e=>setResume(e.target.value)} placeholder="Paste your resume text..."/></div><aside className="panel"><label>ATS-STYLE SCORE</label><div className="score">{score?.score??"—"}<span>/100</span></div>{score&&<><div className="metrics">{Object.entries(score.breakdown).map(([k,v])=><div key={k}><span>{k}</span><b>{String(v)}%</b></div>)}</div><div className="chips">{score.matched.map((x:string)=><i className="good" key={x}>✓ {x}</i>)}{score.related.map((x:string)=><i className="related" key={x}>~ {x}</i>)}{score.missing.map((x:string)=><i className="missing" key={x}>⚠ {x}</i>)}</div></>}<label>AI COACH</label><textarea value={selected} onChange={e=>setSelected(e.target.value)} placeholder="Paste one resume bullet..."/><button className="primary" onClick={fix} disabled={!selected||!jd}>Generate Fix</button>{suggestion&&<div className="suggestion"><label>SUGGESTED FIX</label><p>{suggestion}</p><button className="primary" onClick={apply}>Apply Fix</button><button onClick={fix}>Redo</button></div>}<p className="note">ATS score is a deterministic simulation. AI is instructed not to fabricate experience.</p></aside></section></main>
}